# ------------------------------------------------------------------------------
# Dockerfile for tppcon
# Base image   : ubuntu:20.04
# Maintainer   : Alexey Nesterenko <comcon1@protonmail.com>
# Description  : Base image to faster derive in TPPMKTOP devcontainer
# Version      : 0.3.0-devbase
# Created      : 2025-08-10
# ------------------------------------------------------------------------------

FROM ubuntu:20.04

LABEL org.opencontainers.image.title="tppcon" \
      org.opencontainers.image.description="Container for developing TPPMKTOP" \
      org.opencontainers.image.version="0.3.0-devbase" \
      org.opencontainers.image.url="https://hub.docker.com/r/comcon1/tppcon" \
      org.opencontainers.image.source="https://github.com/comcon1/TPP-docker" \
      org.opencontainers.image.licenses="GPLv3" \
      org.opencontainers.image.vendor="Alexey M. Nesterenko" 

ENV TZ=Europe/Oslo

RUN echo $TZ && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get update -y && \
    apt-get install -y locales && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen && \
    apt-get install -y \
        tzdata \
        wget \
        unzip \
        cmake \
        build-essential \
        autotools-dev \
        autoconf \
        automake \
        libtool \
        git \
        vim && \
    cd && \
    wget https://github.com/openbabel/openbabel/archive/refs/tags/openbabel-2-4-0.zip && \
    unzip openbabel-2-4-0.zip && \
    cd openbabel-openbabel-2-4-0 && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local/openbabel-240 \
          -DBUILD_GUI=OFF -DENABLE_TESTS=OFF -DWITH_INCHI=OFF .. && \
    make -j4 && make install && \
    ls -R /usr/local/openbabel-240 && \
    cd && rm -fr ~/openbabel-openbabel-2-4-0 && \
    apt-get install -y libmysqlclient21 libmysql++3v5 && \
    apt-get install -y libboost-thread1.71.0 libboost-filesystem1.71.0 \
    	 	   libboost-program-options1.71.0 libboost-regex1.71.0 \
    		   libboost-log1.71.0 && \
    apt-get install -y libmysql++-dev && \
    apt-get install -y libboost1.71-dev libboost-thread1.71-dev libboost-filesystem1.71-dev \
    		   libboost-program-options1.71-dev libboost-regex1.71-dev libboost-log1.71-dev && \
    apt-get install -y vim gdb && \
    apt-get -y autoremove --purge && apt-get clean && apt-get purge && \
    rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

CMD ["/bin/bash"]

